name: 'Update i18n deploy'

on:
  schedule:
    - cron: '0 0,12 * * *'

permissions:
  contents: read

jobs:
  deploy:
    name: 'Build and deploy localized site'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # tag: v4.1.1

      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # tag: v4.0.1
        with:
          node-version: 20

      - name: Install dependencies
        uses: bahmutov/npm-install@d476752204653fb5cce6c09db0eaf220761f5d9e # tag: v1.8.37

      - name: Download crowdin translation
        run: yarn i18n:download
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Update Crowdin glossary
        run: yarn i18n:glossary
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      # TODO: figure out if this can be re-enabled?
      # - name: Download cache
      #   run: ./scripts/bin/azcopy copy "https://electronwebsite.blob.core.windows.net/%24web/*?$SAS" "./build" --recursive
      #   env:
      #     SAS: ${{ secrets.SAS }}

      - name: Add Docusaurus problem matcher
        run: echo "::add-matcher::.github/problem-matchers/docusaurus.json"

      - name: Build
        run: yarn i18n:build

      - name: Deploy
        run: ./scripts/bin/azcopy copy "./build/*" "https://electronwebsite.blob.core.windows.net/%24web?$SAS" --recursive
        env:
          SAS: ${{ secrets.SAS }}
